"""Protocol / contract for MailboxMemoryStore implementations."""

from __future__ import annotations

from typing import Any, Protocol


class MailboxMemoryStore(Protocol):
    """Store contract shared by Postgres and test doubles."""

    def bootstrap(self) -> None: ...
    def upsert_case(self, row: dict[str, Any]) -> None: ...
    def upsert_message(self, row: dict[str, Any]) -> None: ...
    def upsert_attachment(self, row: dict[str, Any]) -> None: ...
    def upsert_document(self, row: dict[str, Any]) -> None: ...
    def replace_document_chunks(self, document_id: str, rows: list[dict[str, Any]]) -> None: ...
    def append_event(self, row: dict[str, Any]) -> None: ...
    def replace_message_facts(self, *, message_id: str, rows: list[dict[str, Any]]) -> None: ...
    def append_fact_rows(self, rows: list[dict[str, Any]]) -> None: ...
    def upsert_snapshot(self, case_id: str, row: dict[str, Any]) -> None: ...
    def append_case_snapshot_version(self, row: dict[str, Any]) -> None: ...
    def fetch_case_snapshot_versions(self, case_id: str, *, limit: int = 50) -> list[dict[str, Any]]: ...
    def fetch_latest_case_snapshot_version(self, case_id: str) -> dict[str, Any] | None: ...
    def upsert_next_action(self, case_id: str, row: dict[str, Any]) -> None: ...
    def fetch_case(self, case_id: str) -> dict[str, Any] | None: ...
    def fetch_resolved_cases_by_family_and_fact_keys(
        self,
        *,
        case_family: str,
        fact_keys: list[str],
        exclude_case_id: str = "",
        limit: int = 5,
    ) -> list[dict[str, Any]]: ...
    def fetch_case_by_message_id(self, message_id: str) -> dict[str, Any] | None: ...
    def fetch_message(self, message_id: str) -> dict[str, Any] | None: ...
    def fetch_any_message(self, *, order: str = "oldest") -> dict[str, Any] | None: ...
    def fetch_messages_for_case(self, case_id: str, *, limit: int = 10) -> list[dict[str, Any]]: ...
    def fetch_cases(self, *, limit: int = 200) -> list[dict[str, Any]]: ...
    def fetch_events_for_case(self, case_id: str, *, limit: int = 20) -> list[dict[str, Any]]: ...
    def fetch_events(self, *, event_types: tuple[str, ...] = (), limit: int = 1000) -> list[dict[str, Any]]: ...
    def upsert_action_proposal(self, row: dict[str, Any]) -> None: ...
    def fetch_action_proposal(self, proposal_id: str) -> dict[str, Any] | None: ...
    def fetch_action_proposals(self, *, case_id: str = "", status: str = "", limit: int = 100) -> list[dict[str, Any]]: ...
    def append_policy_decision(self, row: dict[str, Any]) -> bool: ...
    def fetch_policy_decision(self, policy_decision_id: str) -> dict[str, Any] | None: ...
    def fetch_policy_decisions(
        self,
        *,
        case_id: str = "",
        source_signal_id: str = "",
        source_message_id: str = "",
        limit: int = 100,
    ) -> list[dict[str, Any]]: ...
    def append_action_proposal_v2(self, row: dict[str, Any]) -> bool: ...
    def fetch_action_proposal_v2(self, proposal_id: str) -> dict[str, Any] | None: ...
    def fetch_action_proposals_v2(
        self,
        *,
        case_id: str = "",
        source_signal_id: str = "",
        source_message_id: str = "",
        limit: int = 100,
    ) -> list[dict[str, Any]]: ...
    def upsert_execution_result(self, row: dict[str, Any]) -> None: ...
    def fetch_execution_results(self, *, case_id: str = "", proposal_id: str = "", limit: int = 100) -> list[dict[str, Any]]: ...
    def upsert_calendar_event(self, row: dict[str, Any]) -> None: ...
    def upsert_calendar_case_link(self, row: dict[str, Any]) -> None: ...
    def fetch_calendar_events_for_case(self, case_id: str, *, limit: int = 10) -> list[dict[str, Any]]: ...
    def upsert_document_intelligence_result(self, row: dict[str, Any]) -> None: ...
    def fetch_document_intelligence_for_case(self, case_id: str, *, limit: int = 20) -> list[dict[str, Any]]: ...
    def fetch_latest_adjudication_link_override(self, signal_id: str) -> dict[str, Any] | None: ...
    def fetch_facts_for_case(self, case_id: str) -> list[dict[str, Any]]: ...
    def fetch_documents_for_case(self, case_id: str, *, limit: int = 10) -> list[dict[str, Any]]: ...
    def fetch_chunks_for_case(self, case_id: str, *, limit: int = 200) -> list[dict[str, Any]]: ...
    def fetch_snapshot(self, case_id: str) -> dict[str, Any] | None: ...
    def fetch_next_action(self, case_id: str) -> dict[str, Any] | None: ...
    def upsert_drive_document(self, row: dict[str, Any]) -> None: ...
    def replace_drive_document_chunks(self, *, document_id: str, rows: list[dict[str, Any]]) -> None: ...
    def replace_drive_document_facts(self, *, document_id: str, rows: list[dict[str, Any]]) -> None: ...
    def upsert_drive_ingest_run(self, row: dict[str, Any]) -> None: ...
    def fetch_drive_documents_for_case(self, case_id: str, *, limit: int = 10) -> list[dict[str, Any]]: ...
    def fetch_drive_chunks_for_case(self, case_id: str, *, limit: int = 200) -> list[dict[str, Any]]: ...
    def fetch_semantic_chunk_candidates_for_case(
        self, case_id: str, query_vector_literal: str, *, limit_mailbox: int = 50, limit_drive: int = 50
    ) -> list[dict[str, Any]]: ...
    def fetch_drive_facts_for_case(self, case_id: str) -> list[dict[str, Any]]: ...
    def fetch_drive_facts_for_document(self, document_id: str) -> list[dict[str, Any]]: ...
    def fetch_drive_documents(self, *, limit: int = 100, scopes: tuple[str, ...] = (), lanes: tuple[str, ...] = ()) -> list[dict[str, Any]]: ...
    def fetch_drive_document_by_item_id(self, drive_item_id: str) -> dict[str, Any] | None: ...
    def append_raw_observation(self, row: dict[str, Any]) -> bool: ...
    def fetch_raw_observation(self, observation_id: str) -> dict[str, Any] | None: ...
    def fetch_raw_observation_by_source_fingerprint(self, source_fingerprint: str) -> dict[str, Any] | None: ...
    def fetch_raw_observations_for_source(self, source_kind: str, *, limit: int = 200) -> list[dict[str, Any]]: ...
    def append_signal(self, row: dict[str, Any]) -> bool: ...
    def fetch_signal(self, signal_id: str) -> dict[str, Any] | None: ...
    def patch_signal_engagement_id(self, signal_id: str, engagement_id: str) -> bool: ...
    def fetch_signal_by_idempotency_key(self, idempotency_key: str) -> dict[str, Any] | None: ...
    def fetch_signals_for_case(self, case_id: str = "", *, case_key_hint: str = "", limit: int = 200) -> list[dict[str, Any]]: ...
    def fetch_signals_for_source(self, source_kind: str, *, limit: int = 200) -> list[dict[str, Any]]: ...
    def append_signal_processing_attempt(self, row: dict[str, Any]) -> None: ...
    def fetch_signal_processing_attempts(self, signal_id: str, *, limit: int = 50) -> list[dict[str, Any]]: ...
    def upsert_source_cursor(self, row: dict[str, Any]) -> None: ...
    def fetch_source_cursor(self, source_kind: str, cursor_scope: str) -> dict[str, Any] | None: ...
    def list_source_cursors(self) -> list[dict[str, Any]]: ...
