"""Shared type protocols for dependency injection.

Replaces bare `Any` with typed Protocols for DB connections and stores.
"""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class DatabaseConnection(Protocol):
    """Minimal protocol for a DB connection (psycopg2 / psycopg compatible)."""
    def cursor(self) -> Any: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...


@runtime_checkable
class CaseSnapshotStore(Protocol):
    """Store interface for CaseSnapshotManager."""
    def append_fact_rows(self, rows: list[dict[str, Any]]) -> None: ...
    def fetch_case_snapshot_versions(self, case_id: str, limit: int) -> list[dict[str, Any]]: ...
    def fetch_case(self, case_id: str) -> dict[str, Any]: ...
    def fetch_snapshot(self, case_id: str) -> dict[str, Any]: ...
    def fetch_next_action(self, case_id: str) -> dict[str, Any]: ...


@runtime_checkable
class CorrelationStore(Protocol):
    """Store interface for case-email correlation lookups."""
    def find_identity_by_email(self, email: str) -> dict[str, Any] | None: ...
    def find_engagement_for_identity_recent(self, identity_id: str) -> str | None: ...
    def list_links_for_engagement(self, engagement_id: str) -> list[dict[str, Any]]: ...
    def upsert_link(self, engagement_id: str, link_type: str, target_id: str,
                    source_repo: str, confidence: float) -> None: ...
