"""Canonical local artifact contracts for Gmail Intake V1/V2 runs."""

from __future__ import annotations

from collections import Counter
from datetime import datetime
from pathlib import Path
from typing import Any

from intake_policy import (
    CHECK_STATUS_OK,
    DOCTOR_STATUS_OK,
    ERROR_CATEGORIES,
    OUTPUT_ORIGINS,
    PREFLIGHT_STATUS_OK,
    PREFLIGHT_STATUS_WARNING,
    REVIEW_FLAGS,
    RUN_MODE_SHADOW,
    RUN_STAGES,
    RUN_STATUS_RUNNING,
)
from redaction import sanitize_for_storage


RUN_ARTIFACT_FILENAMES = {
    "manifest": "run_manifest.json",
    "checkpoint": "run_checkpoint.json",
    "selection": "selection.json",
    "source_messages": "source_messages.jsonl",
    "triage_results": "triage_results.jsonl",
    "intake_inputs": "intake_inputs.jsonl",
    "stage_records": "stage_records.jsonl",
    "model_raw_responses": "model_raw_responses.jsonl",
    "model_normalized_candidates": "model_normalized_candidates.jsonl",
    "model_repair_attempts": "model_repair_attempts.jsonl",
    "validation_results": "validation_results.jsonl",
    "intake_outputs": "intake_outputs.jsonl",
    "preclassification_results": "preclassification_results.jsonl",
    "intake_results_raw": "intake_results_raw.jsonl",
    "intake_results_final": "intake_results_final.jsonl",
    "case_link_results": "case_link_results.jsonl",
    "business_reasoning_results": "business_reasoning_results.jsonl",
    "reply_draft_results": "reply_draft_results.jsonl",
    "action_plan_results": "action_plan_results.jsonl",
    "case_intelligence_results": "case_intelligence_results.jsonl",
    "mailbox_memory_results": "mailbox_memory_results.jsonl",
    "case_guidance_results": "case_guidance_results.jsonl",
    "attachment_intelligence_results": "attachment_intelligence_results.jsonl",
    "thread_memory_results": "thread_memory_results.jsonl",
    "event_log": "event_log.jsonl",
    "telemetry_events": "telemetry_events.jsonl",
    "projection_previews": "projection_previews.jsonl",
    "signal_projections": "signal_projections.jsonl",
    "case_patches": "case_patches.jsonl",
    "desk_note_patches": "desk_note_patches.jsonl",
    "decision_traces": "decision_traces.jsonl",
    "review_decisions": "review_decisions.jsonl",
    "execution_metadata": "execution_metadata.jsonl",
    "dash_preview": "dash_preview.jsonl",
    "shadow_review_template": "shadow_review_template.csv",
    "human_annotations": "human_annotations.csv",
    "daszek_push_results": "daszek_push_results.jsonl",
    "daszek_v2_push_results": "daszek_v2_push_results.jsonl",
    "daszek_v3_feed_push_results": "daszek_v3_feed_push_results.jsonl",
    "errors": "errors.jsonl",
    "summary": "summary.json",
    "eval_summary": "eval_summary.json",
    "eval_details": "eval_details.json",
    "eval_markdown": "eval_summary.md",
}

STAGE_RESULT_ARTIFACT_KEYS = (
    "preclassification_results",
    "intake_results_raw",
    "intake_results_final",
    "case_link_results",
    "business_reasoning_results",
    "reply_draft_results",
    "action_plan_results",
    "case_intelligence_results",
    "mailbox_memory_results",
    "case_guidance_results",
    "attachment_intelligence_results",
    "thread_memory_results",
    "projection_previews",
    "signal_projections",
    "case_patches",
    "desk_note_patches",
    "decision_traces",
    "review_decisions",
    "execution_metadata",
)

STAGE_ARTIFACT_ENTRY_FIELDS = (
    "message_id",
    "stage_name",
    "lane",
    "status",
    "result",
)

VALIDATION_RESULT_FIELDS = (
    "message_id",
    "inference_mode",
    "is_valid",
    "parse_ok",
    "schema_ok",
    "semantic_ok",
    "raw_valid",
    "normalized_valid",
    "repaired_valid",
    "final_output_origin",
    "guardrail_applied",
    "normalization_applied",
    "normalization_notes",
    "repair_applied",
    "repair_notes",
    "errors",
    "original_action",
    "final_action",
    "guardrail_flags",
)

REVIEW_TEMPLATE_FIELDS = [
    "message_id",
    "subject",
    "sender",
    "agent_preclassification_lane",
    "agent_primary_signal_code",
    "agent_business_area",
    "agent_case_family",
    "agent_decision_action",
    "agent_priority",
    "agent_review_required",
    "agent_review_flags",
    "agent_signal_confidence",
    "agent_case_link_confidence",
    "agent_decision_confidence",
    "agent_case_key",
    "agent_case_key_source",
    "agent_final_output_origin",
    "agent_guardrail_flags",
    "agent_case_link_decision",
    "agent_case_link_selected_key",
    "agent_case_link_stage_confidence",
    "agent_business_interpretation",
    "agent_recommended_next_action",
    "agent_missing_information",
    "agent_operator_note",
    "agent_reply_draft_available",
    "agent_reply_recommended_variant",
    "agent_reply_do_not_send_reasons",
    "agent_action_primary",
    "agent_action_projection_mode",
    "agent_action_safe_for_live_push",
    "expected_primary_signal_code",
    "expected_business_area",
    "expected_case_family",
    "expected_decision_action",
    "expected_priority",
    "expected_review_required",
    "expected_case_key_if_known",
    "expected_key_references",
    "expected_case_link_decision",
    "expected_recommended_next_action",
    "expected_missing_information",
    "expected_operator_note_quality",
    "expected_reply_should_exist",
    "expected_reply_quality",
    "expected_reply_usefulness",
    "expected_action_primary",
    "expected_projection_mode",
    "reviewer_failure_cluster",
    "prompt_change_hint",
    "threshold_change_hint",
    "reviewer_notes",
]

REVIEW_TEMPLATE_FIELD_DESCRIPTIONS = {
    "message_id": "Canonical Gmail message id for matching agent outputs and annotations.",
    "subject": "Source message subject kept for human review context.",
    "sender": "Source sender display string for reviewer context.",
    "agent_preclassification_lane": "Deterministic preclassification lane selected before intake reasoning.",
    "agent_primary_signal_code": "Primary signal predicted by the agent.",
    "agent_business_area": "Business area predicted by the agent.",
    "agent_case_family": "Case family predicted by the agent.",
    "agent_decision_action": "Decision action predicted by the agent.",
    "agent_priority": "Priority predicted by the agent.",
    "agent_review_required": "Agent review gate as lowercase true/false.",
    "agent_review_flags": "Comma-separated review flags emitted by the agent.",
    "agent_signal_confidence": "Formatted signal confidence from the agent output.",
    "agent_case_link_confidence": "Formatted case-link confidence from the agent output.",
    "agent_decision_confidence": "Formatted decision confidence from the agent output.",
    "agent_case_key": "Projected case key that preview/live projection would send downstream, when any.",
    "agent_case_key_source": "Whether the projected case key came from a linked candidate, derivation, or none.",
    "agent_final_output_origin": "Whether the final output was raw-valid, normalized-valid, repaired-valid, or guardrail-downgraded.",
    "agent_guardrail_flags": "Comma-separated guardrail flags that forced the final review downgrade, if any.",
    "agent_case_link_decision": "Deterministic case-link stage decision.",
    "agent_case_link_selected_key": "Case key chosen by the case-link stage, if any.",
    "agent_case_link_stage_confidence": "Confidence returned by the case-link stage.",
    "agent_business_interpretation": "Business reasoning summary or short interpretation.",
    "agent_recommended_next_action": "Business reasoning next-best-action recommendation.",
    "agent_missing_information": "Comma-separated missing-information items from business reasoning.",
    "agent_operator_note": "Operator-facing note produced by business reasoning.",
    "agent_reply_draft_available": "Whether the reply-drafter produced at least one draft variant.",
    "agent_reply_recommended_variant": "Reply variant recommended by the reply-drafter.",
    "agent_reply_do_not_send_reasons": "Comma-separated reasons for not sending or not generating a reply draft.",
    "agent_action_primary": "Primary operator action selected by the action planner.",
    "agent_action_projection_mode": "Projection mode chosen by the action planner.",
    "agent_action_safe_for_live_push": "Whether the action planner considered the result safe for live push.",
    "expected_primary_signal_code": "Human-reviewed target primary signal code.",
    "expected_business_area": "Human-reviewed target business area.",
    "expected_case_family": "Human-reviewed target case family.",
    "expected_decision_action": "Human-reviewed target decision action.",
    "expected_priority": "Human-reviewed target priority.",
    "expected_review_required": "Human-reviewed review gate as true/false.",
    "expected_case_key_if_known": "Known case key when the reviewer can identify the case link.",
    "expected_key_references": "Comma- or semicolon-separated business references expected in extraction.",
    "expected_case_link_decision": "Human-reviewed case-link outcome such as linked, weak_link, no_link, or competing_links.",
    "expected_recommended_next_action": "Human-reviewed next-best action for the operator.",
    "expected_missing_information": "Comma- or semicolon-separated information items the business reasoner should have highlighted.",
    "expected_operator_note_quality": "Expected operator-note quality using strong, usable, or weak.",
    "expected_reply_should_exist": "Whether a useful draft reply should exist: true or false.",
    "expected_reply_quality": "Expected draft quality using strong, usable, weak, or none.",
    "expected_reply_usefulness": "Expected draft usefulness using useful, partial, not_useful, or none.",
    "expected_action_primary": "Human-reviewed primary action that the action planner should select.",
    "expected_projection_mode": "Human-reviewed projection mode expected from the action plan.",
    "reviewer_failure_cluster": "Reviewer-labelled failure cluster(s) for calibration analysis.",
    "prompt_change_hint": "Optional prompt adjustment hint from the reviewer.",
    "threshold_change_hint": "Optional threshold/policy adjustment hint from the reviewer.",
    "reviewer_notes": "Free-text notes for human review context.",
}

RUN_ARTIFACT_CONTRACTS = {
    RUN_ARTIFACT_FILENAMES["manifest"]: {
        "type": "json",
        "required_keys": [
            "run_id",
            "mode",
            "status",
            "command",
            "selector",
            "mailbox",
            "model",
            "runtime_controls",
            "preflight",
            "started_at",
            "completed_at",
        ],
        "description": "Run-level metadata, selector, environment origin, and preflight result.",
    },
    RUN_ARTIFACT_FILENAMES["summary"]: {
        "type": "json",
        "required_keys": [
            "run_id",
            "status",
            "mailbox",
            "items_selected",
            "items_processed",
            "items_valid",
            "items_failed",
            "errors_by_stage",
            "errors_by_category",
            "decision_distribution",
            "review_flag_distribution",
            "validation_origin_distribution",
            "stop_reason",
            "review_template",
            "human_annotations_path",
            "stage_artifacts",
            "runtime_controls",
            "preflight",
            "completed_at",
        ],
        "description": "Final run summary with stable counters and artifact pointers.",
    },
    RUN_ARTIFACT_FILENAMES["validation_results"]: {
        "type": "jsonl",
        "required_keys": list(VALIDATION_RESULT_FIELDS),
        "description": "Per-message parse/schema/semantic validation plus guardrail outcome.",
    },
    RUN_ARTIFACT_FILENAMES["triage_results"]: {
        "type": "jsonl",
        "required_keys": [
            "message_id",
            "observation_id",
            "source_kind",
            "triage_class",
            "routing_decision",
            "reasoning_budget",
            "batching",
            "preclassification",
        ],
        "description": "Per-message cheap triage outputs recorded before heavy reasoning or downstream signal batching.",
    },
    RUN_ARTIFACT_FILENAMES["model_normalized_candidates"]: {
        "type": "jsonl",
        "required_keys": ["message_id", "inference_mode", "candidate", "notes"],
        "description": "Post-normalization candidate JSON used before final validation/repair.",
    },
    RUN_ARTIFACT_FILENAMES["model_repair_attempts"]: {
        "type": "jsonl",
        "required_keys": ["message_id", "inference_mode", "candidate", "notes", "status"],
        "description": "Local repair attempts for parseable-but-invalid model outputs.",
    },
    RUN_ARTIFACT_FILENAMES["stage_records"]: {
        "type": "jsonl",
        "required_keys": [
            "message_id",
            "preclassification_result",
            "intake_result_raw",
            "intake_result_final",
            "case_link_result",
            "business_reasoning_result",
            "reply_draft_result",
            "action_plan_result",
            "mailbox_memory_result",
            "projection_preview",
            "signal_projection",
            "case_patch",
            "desk_note_patch",
            "decision_trace",
            "review_decision",
            "execution_metadata",
        ],
        "description": "Per-message stage trace with named v2 control-plane and shadow-plane outputs.",
    },
    **{
        RUN_ARTIFACT_FILENAMES[key]: {
            "type": "jsonl",
            "required_keys": list(STAGE_ARTIFACT_ENTRY_FIELDS),
            "description": description,
        }
        for key, description in {
            "preclassification_results": "Per-message deterministic preclassification outputs and lane decisions.",
            "intake_results_raw": "Per-message raw intake reasoning outputs before validation.",
            "intake_results_final": "Per-message validated IntakeResult contracts after normalization, repair, and guards.",
            "case_link_results": "Per-message CaseLinkResult contracts from the deterministic case-linker.",
            "business_reasoning_results": "Per-message BusinessReasoningResult contracts or explicit skip/fallback artifacts.",
            "reply_draft_results": "Per-message ReplyDraftResult contracts or explicit skip/fallback artifacts.",
            "action_plan_results": "Per-message ActionPlanResult contracts for the operator action plane.",
            "projection_previews": "Per-message projection-preview stage outputs aligned with dash_preview.jsonl.",
            "mailbox_memory_results": "Per-message Python-owned mailbox-memory ingest/finalize results and context packs.",
            "signal_projections": "Per-message canonical v2 Signal projections emitted in shadow mode.",
            "case_patches": "Per-message canonical v2 Case mutation intents emitted in shadow mode.",
            "desk_note_patches": "Per-message canonical v2 Desk Note mutation intents emitted in shadow mode.",
            "decision_traces": "Per-message canonical v2 Decision Trace entries emitted in shadow mode.",
            "review_decisions": "Per-message review decisions showing whether human review is required and why.",
            "execution_metadata": "Per-message execution metadata including lane plans and stage telemetry.",
        }.items()
    },
    RUN_ARTIFACT_FILENAMES["dash_preview"]: {
        "type": "jsonl",
        "required_keys": ["adapter_version", "target", "decision_action", "message_id", "thread_id", "ignored", "requests"],
        "description": "Per-message preview payloads aligned to the local Daszek contract.",
    },
    RUN_ARTIFACT_FILENAMES["daszek_push_results"]: {
        "type": "jsonl",
        "required_keys": ["request_id", "status", "object_type", "message_id", "task_id", "details"],
        "description": "Per-request live push results against the legacy Daszek v1 task API.",
    },
    RUN_ARTIFACT_FILENAMES["daszek_v2_push_results"]: {
        "type": "jsonl",
        "required_keys": ["status", "message_id", "signal_id", "trace_id", "details"],
        "description": "Per-message live push results against the canonical Daszek v2 ingest API.",
    },
    RUN_ARTIFACT_FILENAMES["shadow_review_template"]: {
        "type": "csv",
        "required_keys": list(REVIEW_TEMPLATE_FIELDS),
        "description": "Human review template seeded with agent predictions.",
    },
    RUN_ARTIFACT_FILENAMES["human_annotations"]: {
        "type": "csv",
        "required_keys": list(REVIEW_TEMPLATE_FIELDS),
        "description": "Human-filled annotations using the same stable columns as the review template.",
    },
    RUN_ARTIFACT_FILENAMES["eval_summary"]: {
        "type": "json",
        "required_keys": [
            "compared_items",
            "missing_outputs",
            "decision_accuracy",
            "signal_accuracy",
            "review_accuracy",
            "case_key_accuracy",
            "reference_recall",
            "failure_clusters",
            "prompt_change_candidates",
            "threshold_change_candidates",
            "calibration_notes",
        ],
        "description": "Aggregate eval metrics and calibration hints derived from human annotations.",
    },
}


def build_run_artifact_paths(run_dir: Path) -> dict[str, Path]:
    """Return canonical artifact paths for a run directory."""
    return {name: run_dir / filename for name, filename in RUN_ARTIFACT_FILENAMES.items()}


def empty_preflight_summary(*, warnings: list[str] | None = None) -> dict[str, Any]:
    """Return an initialized preflight summary."""
    warnings_list = list(warnings or [])
    status = PREFLIGHT_STATUS_OK if not warnings_list else PREFLIGHT_STATUS_WARNING
    return {"status": status, "checks": {}, "warnings": warnings_list}


def empty_doctor_summary() -> dict[str, Any]:
    """Return an initialized doctor summary."""
    return {
        "status": DOCTOR_STATUS_OK,
        "env_source": "",
        "warnings": [],
        "checks": {
            "config": {"status": CHECK_STATUS_OK},
        },
    }


def empty_run_summary() -> dict[str, Any]:
    """Return the mutable in-memory summary counters used during a run."""
    return {
        "items_selected": 0,
        "items_seen": 0,
        "items_fetched": 0,
        "items_processed": 0,
        "items_valid": 0,
        "items_raw_valid": 0,
        "items_normalized_valid": 0,
        "items_repaired_valid": 0,
        "items_guardrail_downgraded": 0,
        "items_invalid_json": 0,
        "items_schema_invalid": 0,
        "items_semantic_invalid": 0,
        "items_failed_preview": 0,
        "items_pushed": 0,
        "items_push_skipped": 0,
        "items_push_failed": 0,
        "items_v1_push_blocked_by_policy": 0,
        "items_v2_pushed": 0,
        "items_v2_push_skipped": 0,
        "items_v2_push_failed": 0,
        "items_v2_push_blocked_by_policy": 0,
        "operational_feed_push_count": 0,
        "operational_feed_push_skipped": 0,
        "operational_feed_push_debounced": 0,
        "operational_feed_push_failed": 0,
        "last_operational_feed_push_monotonic": 0.0,
        "last_operational_feed_snapshot_id": "",
        "last_operational_feed_counts": {},
        "items_failed": 0,
        "errors_by_stage": {stage: 0 for stage in RUN_STAGES},
        "errors_by_category": {category: 0 for category in ERROR_CATEGORIES},
        "decision_distribution": Counter(),
        "review_flag_distribution": Counter({flag: 0 for flag in REVIEW_FLAGS}),
        "validation_origin_distribution": Counter({origin: 0 for origin in OUTPUT_ORIGINS}),
        "consecutive_failures": 0,
        "valid_outputs": [],
        "processed_message_ids": [],
        "failed_items": [],
        "aborted": False,
        "stop_reason": "",
        "stop_details": {},
        "semantic_alignment": {
            "items_with_attachment_envelope": 0,
            "items_with_thread_context_envelope": 0,
            "second_pass_triggers": 0,
            "approx_enrichment_chars_sum": 0,
        },
        "telemetry_enabled": False,
        "otel_export_mode": "disabled",
        "telemetry_event_count": 0,
        "telemetry_mirror_path": "",
        "trace_coverage_summary": {},
        "items_case_guidance_enabled": 0,
        "items_case_guidance_skipped": 0,
        "items_case_guidance_fallback": 0,
        "items_case_guidance_remote_state_used": 0,
    }


def build_run_manifest(
    *,
    run_id: str,
    command: str,
    selector: dict[str, Any],
    mailbox: str,
    model: str,
    schema_path: str | None,
    source_run: str | None,
    push_daszek: bool,
    runtime_controls: dict[str, Any],
) -> dict[str, Any]:
    """Build a stable manifest object for a new run."""
    return {
        "run_id": run_id,
        "mode": RUN_MODE_SHADOW,
        "status": RUN_STATUS_RUNNING,
        "command": command,
        "selector": sanitize_for_storage(selector),
        "mailbox": mailbox,
        "model": model,
        "schema_path": str(Path(schema_path).resolve()) if schema_path else "",
        "source_run": source_run,
        "daszek_push_requested": push_daszek,
        "runtime_controls": sanitize_for_storage(runtime_controls),
        "env_source": "",
        "local_env_files": [],
        "preflight": empty_preflight_summary(),
        "telemetry": {},
        "started_at": datetime.now().astimezone().isoformat(),
        "completed_at": "",
    }


def build_run_checkpoint(run_state: dict[str, Any], *, last_message_id: str = "") -> dict[str, Any]:
    """Build a stable checkpoint snapshot from the mutable run state."""
    summary = run_state["summary"]
    return {
        "run_id": run_state["run_id"],
        "status": run_state["manifest"]["status"],
        "last_updated_at": datetime.now().astimezone().isoformat(),
        "last_message_id": last_message_id,
        "items_selected": summary["items_selected"],
        "items_seen": summary["items_seen"],
        "items_fetched": summary["items_fetched"],
        "items_processed": summary["items_processed"],
        "items_valid": summary["items_valid"],
        "items_raw_valid": summary["items_raw_valid"],
        "items_normalized_valid": summary["items_normalized_valid"],
        "items_repaired_valid": summary["items_repaired_valid"],
        "items_guardrail_downgraded": summary["items_guardrail_downgraded"],
        "items_invalid_json": summary["items_invalid_json"],
        "items_schema_invalid": summary["items_schema_invalid"],
        "items_semantic_invalid": summary["items_semantic_invalid"],
        "items_failed_preview": summary["items_failed_preview"],
        "items_pushed": summary["items_pushed"],
        "items_push_skipped": summary["items_push_skipped"],
        "items_push_failed": summary["items_push_failed"],
        "items_v1_push_blocked_by_policy": summary["items_v1_push_blocked_by_policy"],
        "items_v2_pushed": summary["items_v2_pushed"],
        "items_v2_push_skipped": summary["items_v2_push_skipped"],
        "items_v2_push_failed": summary["items_v2_push_failed"],
        "items_v2_push_blocked_by_policy": summary["items_v2_push_blocked_by_policy"],
        "items_failed": summary["items_failed"],
        "consecutive_failures": summary["consecutive_failures"],
        "aborted": summary["aborted"],
        "stop_reason": summary["stop_reason"],
        "stop_details": sanitize_for_storage(summary["stop_details"]),
        "errors_by_stage": dict(summary["errors_by_stage"]),
        "errors_by_category": dict(summary["errors_by_category"]),
        "decision_distribution": dict(sorted(summary["decision_distribution"].items())),
        "review_flag_distribution": {
            key: value
            for key, value in sorted(summary["review_flag_distribution"].items())
            if value
        },
        "validation_origin_distribution": {
            key: value
            for key, value in sorted(summary["validation_origin_distribution"].items())
            if value
        },
    }


def build_run_summary_record(run_state: dict[str, Any], *, review_template_path: Path) -> dict[str, Any]:
    """Build the final persisted summary for a completed or aborted run."""
    summary = run_state["summary"]
    return {
        "run_id": run_state["run_id"],
        "status": run_state["manifest"]["status"],
        "mailbox": run_state["manifest"]["mailbox"],
        "items_selected": summary["items_selected"],
        "items_seen": summary["items_seen"],
        "items_fetched": summary["items_fetched"],
        "items_processed": summary["items_processed"],
        "items_valid": summary["items_valid"],
        "items_raw_valid": summary["items_raw_valid"],
        "items_normalized_valid": summary["items_normalized_valid"],
        "items_repaired_valid": summary["items_repaired_valid"],
        "items_guardrail_downgraded": summary["items_guardrail_downgraded"],
        "items_invalid_json": summary["items_invalid_json"],
        "items_schema_invalid": summary["items_schema_invalid"],
        "items_semantic_invalid": summary["items_semantic_invalid"],
        "items_failed_preview": summary["items_failed_preview"],
        "items_pushed": summary["items_pushed"],
        "items_push_skipped": summary["items_push_skipped"],
        "items_push_failed": summary["items_push_failed"],
        "items_v1_push_blocked_by_policy": summary["items_v1_push_blocked_by_policy"],
        "items_v2_pushed": summary["items_v2_pushed"],
        "items_v2_push_skipped": summary["items_v2_push_skipped"],
        "items_v2_push_failed": summary["items_v2_push_failed"],
        "items_v2_push_blocked_by_policy": summary["items_v2_push_blocked_by_policy"],
        "items_failed": summary["items_failed"],
        "consecutive_failures": summary["consecutive_failures"],
        "aborted": summary["aborted"],
        "stop_reason": summary["stop_reason"],
        "stop_details": sanitize_for_storage(summary["stop_details"]),
        "errors_by_stage": dict(summary["errors_by_stage"]),
        "errors_by_category": dict(summary["errors_by_category"]),
        "decision_distribution": dict(sorted(summary["decision_distribution"].items())),
        "review_flag_distribution": {
            key: value
            for key, value in sorted(summary["review_flag_distribution"].items())
            if value
        },
        "validation_origin_distribution": {
            key: value
            for key, value in sorted(summary["validation_origin_distribution"].items())
            if value
        },
        "review_template": str(review_template_path),
        "human_annotations_path": str(run_state["artifacts"]["human_annotations"]),
        "stage_records_path": str(run_state["artifacts"].get("stage_records") or ""),
        "stage_artifacts": {
            key: str(run_state["artifacts"][key])
            for key in STAGE_RESULT_ARTIFACT_KEYS
            if key in run_state["artifacts"]
        },
        "daszek_push_requested": bool(run_state["manifest"].get("daszek_push_requested")),
        "daszek_push_connected": bool(run_state["manifest"].get("daszek_push_connected")),
        "runtime_controls": sanitize_for_storage(run_state["manifest"].get("runtime_controls", {})),
        "env_source": run_state["manifest"].get("env_source", ""),
        "preflight": run_state["manifest"].get("preflight", {}),
        "completed_at": run_state["manifest"]["completed_at"],
        "semantic_alignment": sanitize_for_storage(run_state["summary"].get("semantic_alignment") or {}),
        "telemetry_enabled": bool(summary.get("telemetry_enabled")),
        "otel_export_mode": str(summary.get("otel_export_mode") or "disabled"),
        "telemetry_event_count": int(summary.get("telemetry_event_count") or 0),
        "telemetry_mirror_path": str(summary.get("telemetry_mirror_path") or ""),
        "trace_coverage_summary": sanitize_for_storage(summary.get("trace_coverage_summary") or {}),
        "telemetry": sanitize_for_storage(run_state["manifest"].get("telemetry") or {}),
    }


def build_validation_result(
    *,
    message_id: str,
    inference_mode: str,
    is_valid: bool,
    parse_ok: bool,
    schema_ok: bool,
    semantic_ok: bool,
    raw_valid: bool,
    normalized_valid: bool,
    repaired_valid: bool,
    final_output_origin: str,
    guardrail_applied: bool,
    normalization_applied: bool,
    normalization_notes: list[str],
    repair_applied: bool,
    repair_notes: list[str],
    errors: list[str],
    original_action: str,
    final_action: str,
    guardrail_flags: list[str],
) -> dict[str, Any]:
    """Build one validation_results.jsonl record."""
    return {
        "message_id": message_id,
        "inference_mode": inference_mode,
        "is_valid": is_valid,
        "parse_ok": parse_ok,
        "schema_ok": schema_ok,
        "semantic_ok": semantic_ok,
        "raw_valid": raw_valid,
        "normalized_valid": normalized_valid,
        "repaired_valid": repaired_valid,
        "final_output_origin": final_output_origin,
        "guardrail_applied": guardrail_applied,
        "normalization_applied": normalization_applied,
        "normalization_notes": normalization_notes,
        "repair_applied": repair_applied,
        "repair_notes": repair_notes,
        "errors": errors,
        "original_action": original_action,
        "final_action": final_action,
        "guardrail_flags": guardrail_flags,
    }
